### ISSUE TITLE
Sticky Menu on Homepage is not working on chrome

### ISSUE THREAD

**Issue by sedhuait** [2Fwebd/juntos#1]
Hi, 

Stickymenu on homepage is not working on chrome but its working on firefox. 
Please check your demo on chrome. 

http://2f-design.fr/juntos/demo/index.php

**Comment by 2Fwebd** [comment]
Hello, I just checked it works well on my device. What version of chrome and device do you use ?

**Comment by sedhuait** [comment]
I using win 8 with chrome : 39.0.2171.95 m on Dell XPS. 

please check the screenshot attached. 

![image](https://cloud.githubusercontent.com/assets/1628931/5560163/7f6d04da-8d9d-11e4-97fc-d3dfd09fe821.png)

![image](https://cloud.githubusercontent.com/assets/1628931/5560167/d877855a-8d9d-11e4-83c1-fbdabc70a0e7.png)

**Comment by 2Fwebd** [comment]
Hello,
It seems to be a problem with the plugin, do you have any error in the chrome console ?

**Comment by sedhuait** [comment]
No there is no error in the console. And it's not the issue with the plugin. Because other pages( like single event.html) are working properly in chrome

**Comment by 2Fwebd** [comment]
So it is only on the Home page ??? It's definitely really weird ....Do you have the same issue on any other device, because it's really hard to help without seeing the issue.

**Comment by sedhuait** [comment]
Yes this issue is only on homepage. And its coming on chrome browsers on all platforms. 
If you want,  I can help with Team Viewer Access

**Comment by 2Fwebd** [comment]
Thank you, well it do not comes on every platforms because I can't see it on mine ... I'll try on other devices today and I keep you informed. Thank you for the idea but I need the chrome developper toolbar to figure out what's happening.

**Comment by 2Fwebd** [comment]
I tried on 2 computer working with windows and chrome. I still don't see any problem...

**Comment by sedhuait** [comment]
hey i'm getting it even on my friends laptops / mobile phones always. So i suggest team viewer access. 
if you suggest your convenient time then, then i'll share the credentials give you access. 

please suggest at least two timings in IST

**Comment by 2Fwebd** [comment]
Hello, I never did that before so just let me know how to do. I'm ready from now to next 3 hours, let me know.

**Comment by sedhuait** [comment]
pls download team viewer software and my skype id : sedhuraja.n

**Comment by 2Fwebd** [comment]
Should be fixed now ;) Thank you for the feedback !

**Comment by sedhuait** [comment]
hey its again broken. Different Issue now

**Comment by 2Fwebd** [comment]
Can you give me more details please ;)

**Comment by sedhuait** [comment]
it again failing in chrome and and i fixed issue in old menu code ( which was using sticky.js) by removing position 

Before : 
.sticky-wrapper {
    position: relative;
    z-index: 1000;
    margin-bottom: -95px !important;
}

After : 

.sticky-wrapper {
    z-index: 1000;
    margin-bottom: -95px !important;
}
